FROM node:18-alpine

RUN mkdir -p /client/node_modules && chown -R node:node /client
WORKDIR /client

COPY package.json ./

USER node

RUN npm i

WORKDIR /client/app

COPY --chown=node:node . .



# CMD ["npm", "run", "dev"]
# Expose port 3000 for the SvelteKit app and 24678 for Vite's HMR
EXPOSE 3000
EXPOSE 24678

# Run `yarn dev` and set the host to 0.0.0.0 so we can access the web app from outside
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]


