version: "3"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    env_file: ./client/.env

    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./client:/client/app
