version: "3"

services:
  client:
    build:
      context: ./astro
      dockerfile: Dockerfile.dev
    restart: always
    tty: true
    env_file: ./astro/.env

    ports:
      - 5173:5173
      - 24678:24678
    volumes:
      - ./astro:/astro/app
